import { useState, useEffect, useCallback } from "react";

const SEC=[
  {key:"valuation",title:"Valuation",metrics:[{key:"pe",label:"P/E",type:"number"},{key:"fwd_pe",label:"Fwd P/E",type:"number"},{key:"peg",label:"PEG",type:"number"},{key:"ev_ebitda",label:"EV/EBITDA",type:"number"},{key:"valuation_verdict",label:"Notes",type:"text"}],sk:"valuation_score"},
  {key:"profitability",title:"Profitability",metrics:[{key:"gross_margin",label:"Gross %",type:"number"},{key:"op_margin",label:"Op %",type:"number"},{key:"roe",label:"ROE %",type:"number"},{key:"capital_alloc_note",label:"Capital alloc",type:"text"}],sk:"profitability_score"},
  {key:"growth",title:"Growth",metrics:[{key:"rev_growth_ttm",label:"Rev TTM %",type:"number"},{key:"rev_growth_3yr",label:"3yr CAGR %",type:"number"},{key:"growth_source",label:"Source",type:"text"}],sk:"growth_score"},
  {key:"moat",title:"Moat",metrics:[{key:"moat_type",label:"Moat type",type:"text"},{key:"sole_source",label:"Sole-source",type:"text"},{key:"value_chain_pos",label:"Value chain",type:"text"},{key:"nvidia_pattern",label:"NVIDIA-pattern",type:"text"},{key:"competitive_supply",label:"Competition",type:"text"}],sk:"moat_score"},
  {key:"management",title:"Management",metrics:[{key:"cap_alloc_track",label:"Capital alloc",type:"text"},{key:"insider_ownership",label:"Ownership",type:"text"},{key:"governance",label:"Governance",type:"text"},{key:"strategic_vision",label:"Vision",type:"text"}],sk:"management_score"},
  {key:"risk",title:"Risk",metrics:[{key:"cust_concentration",label:"Concentration",type:"text"},{key:"spof",label:"SPOF",type:"text"},{key:"geo_risk",label:"Geo risk",type:"text"},{key:"cyclicality",label:"Cyclicality",type:"text"},{key:"exit_triggers",label:"Exit triggers",type:"text"}],sk:"risk_score"},
];
const QL=[{value:"wonderful",label:"Wonderful",color:"#22c55e"},{value:"good",label:"Good",color:"#3b82f6"},{value:"fair",label:"Fair",color:"#f59e0b"},{value:"bad",label:"Bad",color:"#ef4444"}];
const PL=[{value:"cheap",label:"Cheap",color:"#22c55e"},{value:"fair_price",label:"Fair",color:"#3b82f6"},{value:"high",label:"High",color:"#f59e0b"},{value:"extremely_high",label:"Ext. High",color:"#ef4444"}];
const MX={"wonderful+cheap":{l:"Strong conviction",c:"#22c55e"},"wonderful+fair_price":{l:"Buy",c:"#22c55e"},"wonderful+high":{l:"Watch for pullback",c:"#f59e0b"},"wonderful+extremely_high":{l:"Admire, don't buy",c:"#f59e0b"},"good+cheap":{l:"Buy",c:"#3b82f6"},"good+fair_price":{l:"Consider",c:"#3b82f6"},"good+high":{l:"Needs catalyst",c:"#f59e0b"},"good+extremely_high":{l:"Pass on price",c:"#ef4444"},"fair+cheap":{l:"Cigar butt",c:"#f59e0b"},"fair+fair_price":{l:"Marginal",c:"#f59e0b"},"fair+high":{l:"Pass",c:"#ef4444"},"fair+extremely_high":{l:"Pass",c:"#ef4444"},"bad+cheap":{l:"Value trap",c:"#ef4444"},"bad+fair_price":{l:"Pass",c:"#ef4444"},"bad+high":{l:"Pass",c:"#ef4444"},"bad+extremely_high":{l:"Pass",c:"#ef4444"}};
const gv=(q,p)=>MX[`${q}+${p}`]||{l:"–",c:"rgba(255,255,255,0.3)"};
const cavg=s=>{const v=Object.values(s||{}).filter(v=>v>0);return v.length?(v.reduce((a,b)=>a+b,0)/v.length).toFixed(1):"–";};
const srt=a=>a.sort((a,b)=>{const x=cavg(a.scores),y=cavg(b.scores);return(y==="–"?0:parseFloat(y))-(x==="–"?0:parseFloat(x));});

const SEED=[
{id:"s_msft",ticker:"MSFT",company:"Microsoft",price:"412",date:"2026-05-13",quality:"wonderful",price_level:"fair_price",metrics:{pe:34,fwd_pe:25,peg:0.76,ev_ebitda:24,valuation_verdict:"PEG 0.76. Azure +40%. AI margins 'better than cloud' (Amy Hood). RPO $627B.",gross_margin:70,op_margin:46,roe:37,capital_alloc_note:"46% op margin even with AI investment. Cloud $54.5B +29%. AI $37B ARR +123%. Copilot 20M seats +250%. $190B capex CY2026.",rev_growth_ttm:16,rev_growth_3yr:15,growth_source:"Azure +40%. AI $37B ARR. Copilot 20M seats. RPO $627B +99%."},scores:{valuation_score:7,profitability_score:9,growth_score:8,moat_score:10,management_score:10,risk_score:9},bull:"PEG 0.76. 70% GM, 46% op. Azure +40%. Satya Nadella. Lowest cyclicality.",bear:"34x TTM. $190B capex. OpenAI dependency."},
{id:"s_meta",ticker:"META",company:"Meta Platforms",price:"600",date:"2026-05-13",quality:"wonderful",price_level:"cheap",metrics:{pe:23,fwd_pe:15,peg:0.39,ev_ebitda:14,valuation_verdict:"Fwd 15x. PEG 0.39 cheapest in universe. Revenue +33% with 41% op margin. Premarket -7% = entry.",gross_margin:82,op_margin:41,roe:68,capital_alloc_note:"Revenue $56.3B +33%. Op income $22.9B. Capex $19.8B Q1. FY26 guided $125-145B. FCF compressed. Named Broadcom for custom silicon.",rev_growth_ttm:33,rev_growth_3yr:18,growth_source:"Ad revenue +33%. AI ranking driving +6% conversion. Value Optimization $20B ARR. 8M advertisers using GenAI creative."},scores:{valuation_score:9,profitability_score:10,growth_score:9,moat_score:9,management_score:8,risk_score:6},bull:"PEG 0.39 cheapest. 82% GM, 68% ROE. Revenue +33% accelerating. Fwd 15x.",bear:"$125-145B capex raised. FCF dropping. Zuckerberg dual-class. Reality Labs burn."},
{id:"s_googl",ticker:"GOOGL",company:"Alphabet (Google)",price:"402",date:"2026-05-13",quality:"wonderful",price_level:"fair_price",metrics:{pe:40,fwd_pe:28,peg:0.97,ev_ebitda:22,valuation_verdict:"Cloud +63%, margin doubled to 32.9%. Backlog $462B. Fwd 28x. Cheapest mega-cap on EV/EBITDA.",gross_margin:58,op_margin:32,roe:18,capital_alloc_note:"Cloud op income TRIPLED to $6.6B. Cloud margin 32.9% (from 17.8%). $97B cash. $70B buyback. Capex $180-190B.",rev_growth_ttm:20,rev_growth_3yr:15,growth_source:"Cloud +63% to $20B. GenAI +800%. Search +19%. Backlog $462B doubled QoQ. Anthropic on TPUs."},scores:{valuation_score:7,profitability_score:9,growth_score:9,moat_score:10,management_score:8,risk_score:8},bull:"Cloud +63%. Margin doubled. Backlog $462B. GenAI +800%. Fwd 28x. Anthropic validates TPUs.",bear:"40x TTM post-jump. $180-190B capex. GCP still #3 by share. Antitrust."},
{id:"s_anet",ticker:"ANET",company:"Arista Networks",price:"~126",date:"2026-04-30",quality:"wonderful",price_level:"fair_price",metrics:{pe:46,fwd_pe:36,peg:1.65,ev_ebitda:38,valuation_verdict:"46x near 10yr avg 43x. ZERO debt. $8.1B cash.",gross_margin:64,op_margin:43,roe:31,capital_alloc_note:"ZERO debt. $8.1B cash. ROIC 177%. Net margin 39%.",rev_growth_ttm:29,rev_growth_3yr:22,growth_source:"AI DC networking. 800G/1.6T. EOS software lock-in."},scores:{valuation_score:6,profitability_score:10,growth_score:8,moat_score:9,management_score:10,risk_score:7},bull:"64% GM, ROIC 177% — ZERO debt. EOS lock-in. Jayshree Ullal.",bear:"46x PE. Nvidia entering networking 2027-28."},
{id:"s_hoya",ticker:"7741.T",company:"Hoya Corporation",price:"~17,500 JPY",date:"2026-05-07",quality:"wonderful",price_level:"fair_price",metrics:{pe:32,fwd_pe:28,peg:2.41,ev_ebitda:19.5,valuation_verdict:"32x. Cheaper than ASML (50x) for equally essential EUV position. Beta 0.61.",gross_margin:86,op_margin:27,roe:21,capital_alloc_note:"86% GM. Net cash ¥497B. D/E 0.04. ROIC 64%. Buybacks -1.22%. IT <30% rev but >50% profit.",rev_growth_ttm:13.6,rev_growth_3yr:10,growth_source:"EUV blanks 75%+ share. ONLY vendor qualified High-NA EUV. HDD substrates (AI storage). Eyeglass lenses stable."},scores:{valuation_score:7,profitability_score:9,growth_score:7,moat_score:10,management_score:8,risk_score:8},bull:"86% GM. 75%+ EUV share. ONLY High-NA qualified. Consumable. Debt-free. ROIC 64%.",bear:"PEG 2.41. Life care dampens growth. Op margin 27% diluted by life care."},
{id:"s_tsm",ticker:"TSM",company:"TSMC",price:"412",date:"2026-05-13",quality:"wonderful",price_level:"fair_price",metrics:{pe:30,fwd_pe:22,peg:1.0,ev_ebitda:19,valuation_verdict:"Fwd 22 monopoly-adjacent. PEG 1.0.",gross_margin:57,op_margin:47,roe:35,capital_alloc_note:"ROE 35%, ROIC 48%. D/E 0.20.",rev_growth_ttm:30,rev_growth_3yr:20,growth_source:"AI/HPC. 3nm. 2nm 2026. CoWoS."},scores:{valuation_score:7,profitability_score:10,growth_score:8,moat_score:10,management_score:9,risk_score:5},bull:"Monopoly-adjacent. 57% GM, 47% op. Fwd 22.",bear:"Taiwan risk existential."},
{id:"s_asml",ticker:"ASML",company:"ASML Holding",price:"~1,478",date:"2026-04-24",quality:"wonderful",price_level:"fair_price",metrics:{pe:50,fwd_pe:40,peg:2.02,ev_ebitda:36,valuation_verdict:"50x monopoly.",gross_margin:53,op_margin:35,roe:50,capital_alloc_note:"ROE 50%, ROIC 68%. D/E 0.24.",rev_growth_ttm:31,rev_growth_3yr:18,growth_source:"EUV. High-NA. Installed base."},scores:{valuation_score:5,profitability_score:10,growth_score:8,moat_score:10,management_score:9,risk_score:6},bull:"Literal monopoly. ROE 50%, ROIC 68%.",bear:"50x. China limits."},
{id:"s_avgo",ticker:"AVGO",company:"Broadcom Inc",price:"428",date:"2026-05-13",quality:"wonderful",price_level:"high",metrics:{pe:72,fwd_pe:33,peg:0.68,ev_ebitda:50,valuation_verdict:"PEG 0.68. Meta named AVGO for 1GW+ custom silicon Q1.",gross_margin:68,op_margin:38,roe:33,capital_alloc_note:"Hock Tan legendary. D/E 0.83 VMware.",rev_growth_ttm:24,rev_growth_3yr:20,growth_source:"Custom AI XPUs. Networking. VMware. Meta validated."},scores:{valuation_score:6,profitability_score:9,growth_score:8,moat_score:9,management_score:10,risk_score:6},bull:"Dual moat. PEG 0.68. Meta validated custom silicon.",bear:"72x TTM. $1.8T cap."},
{id:"s_jcu",ticker:"4975.T",company:"JCU Corporation",price:"~6,070 JPY",date:"2026-04-24",quality:"wonderful",price_level:"cheap",metrics:{pe:15.3,fwd_pe:16,peg:1.7,ev_ebitda:10,valuation_verdict:"15x vs Western comps 35-40x.",gross_margin:69,op_margin:39,roe:17,capital_alloc_note:"Fortress: 24.8B JPY cash. Buybacks.",rev_growth_ttm:3.8,rev_growth_3yr:14,growth_source:"Semi packaging chemicals. Kumamoto."},scores:{valuation_score:8,profitability_score:9,growth_score:6,moat_score:8,management_score:7,risk_score:8},bull:"69% gross/39% op at 15x. Consumable. Fortress balance sheet.",bear:"Modest growth. Japan discount."},
{id:"s_klac",ticker:"KLAC",company:"KLA Corporation",price:"~1,480",date:"2026-04-24",quality:"wonderful",price_level:"high",metrics:{pe:43,fwd_pe:36,peg:2.42,ev_ebitda:34,valuation_verdict:"43x vs 22x avg.",gross_margin:62,op_margin:42,roe:101,capital_alloc_note:"ROE 101%. ROIC 73%.",rev_growth_ttm:17,rev_growth_3yr:12,growth_source:"Process control grows with complexity."},scores:{valuation_score:4,profitability_score:10,growth_score:7,moat_score:10,management_score:9,risk_score:6},bull:"50% share 10+ years. 101% ROE.",bear:"43x vs 22x avg."},
{id:"s_cdns",ticker:"CDNS",company:"Cadence Design",price:"~345",date:"2026-04-24",quality:"wonderful",price_level:"extremely_high",metrics:{pe:93,fwd_pe:50,peg:3.0,ev_ebitda:60,valuation_verdict:"93x. Most expensive.",gross_margin:88,op_margin:30,roe:25,capital_alloc_note:"88% GM highest. Clean.",rev_growth_ttm:15,rev_growth_3yr:15,growth_source:"EDA. System design."},scores:{valuation_score:2,profitability_score:9,growth_score:6,moat_score:10,management_score:8,risk_score:9},bull:"88% GM. Zero cyclicality.",bear:"93x. PEG 3.0."},
{id:"s_snps",ticker:"SNPS",company:"Synopsys Inc",price:"~530",date:"2026-04-24",quality:"wonderful",price_level:"extremely_high",metrics:{pe:81,fwd_pe:45,peg:2.5,ev_ebitda:55,valuation_verdict:"81x. Ansys compressed margins.",gross_margin:75,op_margin:11,roe:15,capital_alloc_note:"75% GM. Ansys $35B.",rev_growth_ttm:32,rev_growth_3yr:15,growth_source:"EDA + Ansys."},scores:{valuation_score:3,profitability_score:7,growth_score:7,moat_score:10,management_score:7,risk_score:9},bull:"EDA duopoly. 75% GM.",bear:"81x. Ansys compressed."},
{id:"s_advt",ticker:"6857.T",company:"Advantest Corp",price:"~25,000 JPY",date:"2026-04-24",quality:"wonderful",price_level:"extremely_high",metrics:{pe:56,fwd_pe:35,peg:1.2,ev_ebitda:40,valuation_verdict:"56x expensive for Japan.",gross_margin:62,op_margin:39,roe:48,capital_alloc_note:"ROE 48%. Capacity expanding.",rev_growth_ttm:30,rev_growth_3yr:15,growth_source:"AI chip testing. 30-40% guided."},scores:{valuation_score:4,profitability_score:9,growth_score:8,moat_score:9,management_score:7,risk_score:6},bull:"#1 tester. 62% GM, 48% ROE.",bear:"56x for Japan."},
{id:"s_amzn",ticker:"AMZN",company:"Amazon",price:"269",date:"2026-05-13",quality:"wonderful",price_level:"high",metrics:{pe:55,fwd_pe:42,peg:1.8,ev_ebitda:22,valuation_verdict:"55x. AWS +28% but FCF crashed to $1.2B.",gross_margin:49,op_margin:11,roe:14,capital_alloc_note:"AWS $37.6B +28%. AWS AI $20B+ ARR. Backlog $364B. Q1 capex $43.2B. FCF $1.2B TTM.",rev_growth_ttm:11,rev_growth_3yr:12,growth_source:"AWS +28% (fastest in 15 quarters). Trainium $225B+ commitments. Bedrock +170% QoQ."},scores:{valuation_score:4,profitability_score:6,growth_score:8,moat_score:10,management_score:8,risk_score:7},bull:"AWS +28%. $364B+ backlog. Trainium $225B+ commitments.",bear:"FCF $1.2B. $43.2B Q1 capex. Azure/GCP outpacing."},
{id:"s_besi",ticker:"BESI.AS",company:"BE Semiconductor",price:"~130 EUR",date:"2026-04-24",quality:"wonderful",price_level:"high",metrics:{pe:66,fwd_pe:51,peg:1.47,ev_ebitda:54,valuation_verdict:"66x. JCU similar at 15x.",gross_margin:64,op_margin:26,roe:36,capital_alloc_note:"95% payout. FCF machine.",rev_growth_ttm:8.5,rev_growth_3yr:5,growth_source:"Hybrid bonding. Orders +105%."},scores:{valuation_score:4,profitability_score:9,growth_score:7,moat_score:9,management_score:8,risk_score:5},bull:"THE hybrid bonding leader. 64% GM, 36% ROE.",bear:"66x. Cyclicality."},
{id:"s_crdo",ticker:"CRDO",company:"Credo Technology",price:"~112",date:"2026-04-24",quality:"good",price_level:"fair_price",metrics:{pe:59,fwd_pe:24,peg:0.32,ev_ebitda:53,valuation_verdict:"PEG misleading — unsustainable denominator.",gross_margin:68,op_margin:30,roe:27.5,capital_alloc_note:"Fabless. $1.3B cash. ROIC 60%.",rev_growth_ttm:226,rev_growth_3yr:80,growth_source:"AEC buildout — moat expiring. ZeroFlap unproven."},scores:{valuation_score:7,profitability_score:8,growth_score:10,moat_score:5,management_score:8,risk_score:4},bull:"200%+ growth, 68% GM, ROIC 60%.",bear:"AEC moat expiring. PEG misleading."},
{id:"s_mrvl",ticker:"MRVL",company:"Marvell Technology",price:"164",date:"2026-05-13",quality:"good",price_level:"extremely_high",metrics:{pe:56,fwd_pe:35,peg:1.4,ev_ebitda:45,valuation_verdict:"DOUBLED from $80. P/E expanded 28→56. Market priced in custom silicon thesis. NVIDIA partnership news catalyst.",gross_margin:52,op_margin:15,roe:18,capital_alloc_note:"ROIC 6% goodwill drag. Record rev $8.2B. Market cap $144B.",rev_growth_ttm:42,rev_growth_3yr:15,growth_source:"Custom AI XPUs. Electro-optics. NVIDIA partnership."},scores:{valuation_score:3,profitability_score:6,growth_score:9,moat_score:7,management_score:7,risk_score:5},bull:"Custom silicon validated by hyperscaler earnings. NVIDIA partnership. 42% growth.",bear:"56x PE vs 28x two weeks ago. ROIC 6%. +105% in weeks — mean reversion risk."},
{id:"s_camt",ticker:"CAMT",company:"Camtek Ltd",price:"~162",date:"2026-04-24",quality:"good",price_level:"fair_price",metrics:{pe:41,fwd_pe:35,peg:1.05,ev_ebitda:30,valuation_verdict:"PEG 1.05 fair.",gross_margin:51,op_margin:29,roe:25,capital_alloc_note:"$794M cash. ROE 25%.",rev_growth_ttm:16,rev_growth_3yr:25,growth_source:"Adv packaging inspection."},scores:{valuation_score:6,profitability_score:7,growth_score:7,moat_score:6,management_score:7,risk_score:5},bull:"PEG 1.05. Hawk winning.",bear:"KLA gorilla."},
{id:"s_glw",ticker:"GLW",company:"Corning Inc",price:"~155",date:"2026-04-24",quality:"wonderful",price_level:"high",metrics:{pe:83,fwd_pe:49,peg:1.36,ev_ebitda:37,valuation_verdict:"83x rich for materials.",gross_margin:36,op_margin:20,roe:15,capital_alloc_note:"FCF $1.72B. Debt $7.63B.",rev_growth_ttm:14,rev_growth_3yr:10,growth_source:"Optical +35%. Meta deal."},scores:{valuation_score:4,profitability_score:6,growth_score:7,moat_score:9,management_score:8,risk_score:7},bull:"170yr moat. Optical backbone.",bear:"83x. $7.63B debt."},
{id:"s_amat",ticker:"AMAT",company:"Applied Materials",price:"~330",date:"2026-04-24",quality:"wonderful",price_level:"high",metrics:{pe:38,fwd_pe:34,peg:3.2,ev_ebitda:29,valuation_verdict:"38x vs 21x avg. PEG 3.2.",gross_margin:49,op_margin:30,roe:35.5,capital_alloc_note:"Buybacks -3.1%.",rev_growth_ttm:-2,rev_growth_3yr:8,growth_source:"Leading-edge + HBM."},scores:{valuation_score:5,profitability_score:8,growth_score:5,moat_score:8,management_score:8,risk_score:5},bull:"Broadest WFE. ROE 35.5%.",bear:"38x vs 21x. China 30%."},
{id:"s_lrcx",ticker:"LRCX",company:"Lam Research",price:"~265",date:"2026-04-24",quality:"wonderful",price_level:"high",metrics:{pe:45,fwd_pe:36,peg:1.81,ev_ebitda:37,valuation_verdict:"45x vs 19x avg.",gross_margin:48,op_margin:30,roe:66,capital_alloc_note:"ROE 66%, ROIC 75%.",rev_growth_ttm:20,rev_growth_3yr:10,growth_source:"Memory recovery. HBM etch."},scores:{valuation_score:4,profitability_score:9,growth_score:7,moat_score:8,management_score:7,risk_score:4},bull:"#1 etch. ROE 66%, ROIC 75%.",bear:"45x vs 19x. Highest cyclicality."},
{id:"s_fn",ticker:"FN",company:"Fabrinet",price:"~500",date:"2026-04-24",quality:"good",price_level:"high",metrics:{pe:50,fwd_pe:34,peg:1.89,ev_ebitda:41,valuation_verdict:"50x vs 20x avg.",gross_margin:12,op_margin:9.8,roe:18,capital_alloc_note:"Debt-free. $962M cash.",rev_growth_ttm:25,rev_growth_3yr:16,growth_source:"1.6T ramp. Building 10."},scores:{valuation_score:4,profitability_score:5,growth_score:8,moat_score:8,management_score:7,risk_score:4},bull:"Sole-source 1.6T center.",bear:"Extreme concentration. 12% GM."},
{id:"s_cohr",ticker:"COHR",company:"Coherent Corp",price:"~254",date:"2026-04-24",quality:"good",price_level:"high",metrics:{pe:210,fwd_pe:35,peg:1.11,ev_ebitda:50,valuation_verdict:"TTM distorted. Fwd 35.",gross_margin:39,op_margin:15,roe:3.2,capital_alloc_note:"Post-merger. D/E 0.40.",rev_growth_ttm:17.5,rev_growth_3yr:12,growth_source:"1.6T. OCS. InP."},scores:{valuation_score:5,profitability_score:5,growth_score:7,moat_score:8,management_score:6,risk_score:6},bull:"Vertically integrated. InP bottleneck.",bear:"GAAP ROE 3%."},
{id:"s_lite",ticker:"LITE",company:"Lumentum Holdings",price:"~870",date:"2026-04-24",quality:"good",price_level:"extremely_high",metrics:{pe:273,fwd_pe:57,peg:0.56,ev_ebitda:45,valuation_verdict:"Up 1,693%. D/E 3.92.",gross_margin:42.5,op_margin:25.2,roe:29.3,capital_alloc_note:"D/E 3.92. Dilution +12.9%.",rev_growth_ttm:65,rev_growth_3yr:20,growth_source:"OCS $400M+."},scores:{valuation_score:3,profitability_score:7,growth_score:9,moat_score:8,management_score:7,risk_score:4},bull:"OCS $400M+.",bear:"D/E 3.92. Up 1,693%."},
{id:"s_vrt",ticker:"VRT",company:"Vertiv Holdings",price:"~295",date:"2026-04-24",quality:"good",price_level:"extremely_high",metrics:{pe:77,fwd_pe:43,peg:1.33,ev_ebitda:46,valuation_verdict:"Industrials at tech multiples.",gross_margin:38,op_margin:18,roe:42,capital_alloc_note:"B2B 2.9x. Backlog $15B.",rev_growth_ttm:28,rev_growth_3yr:20,growth_source:"DC power/cooling."},scores:{valuation_score:3,profitability_score:7,growth_score:8,moat_score:6,management_score:6,risk_score:6},bull:"B2B 2.9x. $15B backlog.",bear:"77x industrials."},
{id:"s_mtsi",ticker:"MTSI",company:"MACOM Technology",price:"~237",date:"2026-04-24",quality:"good",price_level:"extremely_high",metrics:{pe:104,fwd_pe:56,peg:2.5,ev_ebitda:53,valuation_verdict:"Most expensive growth-adjusted.",gross_margin:56,op_margin:16,roe:13,capital_alloc_note:"$768M cash.",rev_growth_ttm:24.5,rev_growth_3yr:15,growth_source:"DC 35-40%."},scores:{valuation_score:3,profitability_score:6,growth_score:7,moat_score:6,management_score:6,risk_score:7},bull:"Diversified. 6,500+ customers.",bear:"PEG 2.5. ROE 13%."},
{id:"s_lsrc",ticker:"6920.T",company:"Lasertec Corporation",price:"~45,000 JPY",date:"2026-05-07",quality:"good",price_level:"high",metrics:{pe:47,fwd_pe:35,peg:1.5,ev_ebitda:30,valuation_verdict:"47x. Analyst target ¥35,175 BELOW price. Scorpion Capital fraud allegations June 2024.",gross_margin:56,op_margin:50,roe:49,capital_alloc_note:"ROE 49% but cash conversion only 65% (vs ASML 130-180%). Inventory highest in semicap. Backlog ¥1.4T+.",rev_growth_ttm:15,rev_growth_3yr:25,growth_source:"EUV mask inspection monopoly. ACTIS A200HiT for High-NA. But Q3 revenue -57% QoQ (lumpy)."},scores:{valuation_score:4,profitability_score:7,growth_score:7,moat_score:7,management_score:5,risk_score:3},bull:"90%+ EUV mask inspection monopoly. ROE 49%. Backlog ¥1.4T+.",bear:"Scorpion fraud allegations. KLA entry 'catastrophic'. Cash conversion 65%. Analyst target below price."},
];

const empty=()=>({ticker:"",company:"",price:"",date:new Date().toISOString().slice(0,10),metrics:{},scores:{},quality:"",price_level:"",bull:"",bear:"",id:Date.now().toString()});
function SB({value:v}){return (<div style={{display:"flex",gap:1.5,alignItems:"center"}}>{[1,2,3,4,5,6,7,8,9,10].map(i=><div key={i} style={{width:5,height:14,borderRadius:2,background:i<=v?v>=8?"#22c55e":v>=5?"#f59e0b":"#ef4444":"rgba(255,255,255,0.05)"}}/>)}<span style={{marginLeft:3,fontSize:9,color:"rgba(255,255,255,0.3)"}}>{v||"–"}</span></div>)}
function VB({quality:q,price_level:p}){const v=gv(q,p);const qo=QL.find(x=>x.value===q);const po=PL.find(x=>x.value===p);if(!qo||!po) return (<span style={{fontSize:9,color:"rgba(255,255,255,0.15)"}}>Not rated</span>);return (<div style={{display:"flex",flexDirection:"column",gap:1}}><div style={{display:"flex",gap:3,alignItems:"center",flexWrap:"wrap"}}><span style={{fontSize:9,padding:"1px 5px",borderRadius:3,background:qo.color+"22",color:qo.color,fontWeight:500}}>{qo.label}</span><span style={{fontSize:8,color:"rgba(255,255,255,0.2)"}}>@</span><span style={{fontSize:9,padding:"1px 5px",borderRadius:3,background:po.color+"22",color:po.color,fontWeight:500}}>{po.label}</span></div><span style={{fontSize:9,color:v.c,fontWeight:500}}>→ {v.l}</span></div>)}

export default function App(){
  const[cards,setCards]=useState([]);const[act,setAct]=useState(null);const[view,setView]=useState("list");const[cmp,setCmp]=useState([]);const[ld,setLd]=useState(true);const[os,setOs]=useState(null);
  const load=useCallback(async()=>{try{const r=await window.storage.list("sc7:");if(r?.keys?.length>0){const d=[];for(const k of r.keys){try{const x=await window.storage.get(k);if(x?.value)d.push(JSON.parse(x.value));}catch{}}srt(d);setCards(d);}else{for(const s of SEED){try{await window.storage.set(`sc7:${s.id}`,JSON.stringify(s));}catch{}}setCards(srt([...SEED]));}}catch{setCards(srt([...SEED]));}finally{setLd(false);}},[]); 
  useEffect(()=>{load();},[load]);
  const sv=async c=>{try{await window.storage.set(`sc7:${c.id}`,JSON.stringify(c));}catch{}};
  const dl=async id=>{try{await window.storage.delete(`sc7:${id}`);}catch{}setCards(p=>p.filter(c=>c.id!==id));if(act?.id===id){setAct(null);setView("list");}};
  const doSv=async()=>{await sv(act);setCards(p=>{const i=p.findIndex(c=>c.id===act.id);if(i>=0){const n=[...p];n[i]=act;return srt(n);}return srt([act,...p]);});setView("list");};
  const uM=(k,v)=>setAct(p=>({...p,metrics:{...p.metrics,[k]:v}}));
  const uS=(k,v)=>setAct(p=>({...p,scores:{...p.scores,[k]:Math.min(10,Math.max(0,parseInt(v)||0))}}));
  const tC=id=>setCmp(p=>p.includes(id)?p.filter(x=>x!==id):p.length<5?[...p,id]:p);
  const F="'JetBrains Mono',monospace";const B="'Inter',sans-serif";
  const base={minHeight:"100vh",background:"#09090b",color:"#e4e4e7",fontFamily:B,padding:"16px 12px"};
  const fonts=<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"/>;
  if(ld) return (<div style={base}>{fonts}<p style={{color:"rgba(255,255,255,0.3)",textAlign:"center",marginTop:80}}>Loading...</p></div>);

  if(view==="compare"){const sel=cards.filter(c=>cmp.includes(c.id));return (<div style={base}>{fonts}<div style={{maxWidth:1400,margin:"0 auto"}}><button onClick={()=>setView("list")} style={lnk}>← Back</button><h1 style={{fontFamily:F,fontSize:14,fontWeight:500,margin:"6px 0 12px"}}>Comparison</h1><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr><th style={th}></th>{sel.map(c=><th key={c.id} style={{...th,textAlign:"center",fontFamily:F,fontSize:11}}>{c.ticker}<br/><span style={{fontSize:8,fontWeight:400,color:"rgba(255,255,255,0.2)"}}>{c.company}</span></th>)}</tr></thead><tbody>
  <tr style={{background:"rgba(255,255,255,0.02)"}}><td style={tdL}>Composite</td>{sel.map(c=>{const a=cavg(c.scores);return (<td key={c.id} style={{...td,textAlign:"center",fontFamily:F,fontSize:16,fontWeight:600,color:a>=7.5?"#22c55e":a>=5?"#f59e0b":"#ef4444"}}>{a}</td>)})}</tr>
  {SEC.map(s=><tr key={s.key}><td style={tdL}>{s.title}</td>{sel.map(c=><td key={c.id} style={{...td,textAlign:"center"}}><SB value={c.scores?.[s.sk]||0}/></td>)}</tr>)}
  <tr style={{background:"rgba(255,255,255,0.02)"}}><td style={tdL}>Verdict</td>{sel.map(c=>{const v=gv(c.quality,c.price_level);return (<td key={c.id} style={{...td,textAlign:"center"}}><span style={{color:v.c,fontSize:9,fontWeight:500}}>{v.l}</span></td>)})}</tr>
  {[{key:"pe",l:"P/E"},{key:"fwd_pe",l:"Fwd"},{key:"peg",l:"PEG"},{key:"gross_margin",l:"GM%"},{key:"op_margin",l:"Op%"},{key:"roe",l:"ROE%"},{key:"rev_growth_ttm",l:"Rev%"}].map(m=><tr key={m.key}><td style={tdL}>{m.l}</td>{sel.map(c=><td key={c.id} style={{...td,textAlign:"center",fontFamily:F}}>{c.metrics?.[m.key]??"–"}</td>)}</tr>)}
  <tr><td style={tdL}>Bull</td>{sel.map(c=><td key={c.id} style={{...td,fontSize:9,lineHeight:1.4}}>{c.bull||"–"}</td>)}</tr>
  <tr><td style={tdL}>Bear</td>{sel.map(c=><td key={c.id} style={{...td,fontSize:9,lineHeight:1.4}}>{c.bear||"–"}</td>)}</tr>
  </tbody></table></div></div></div>)}

  if(view==="edit"&&act){return (<div style={base}>{fonts}<div style={{maxWidth:640,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between"}}><button onClick={()=>setView("list")} style={lnk}>← Cancel</button><button onClick={doSv} style={{...btn,background:"#22c55e",color:"#09090b",fontWeight:600}}>Save</button></div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,margin:"10px 0"}}><div><label style={lb}>Ticker</label><input style={inp} value={act.ticker} onChange={e=>setAct(p=>({...p,ticker:e.target.value.toUpperCase()}))}/></div><div><label style={lb}>Price</label><input style={inp} value={act.price} onChange={e=>setAct(p=>({...p,price:e.target.value}))}/></div><div style={{gridColumn:"1/-1"}}><label style={lb}>Company</label><input style={inp} value={act.company} onChange={e=>setAct(p=>({...p,company:e.target.value}))}/></div></div>
  {SEC.map(sec=>{const o=os===sec.key;return (<div key={sec.key} style={{borderTop:"1px solid rgba(255,255,255,0.04)"}}><div onClick={()=>setOs(o?null:sec.key)} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:5}}><h2 style={{fontFamily:F,fontSize:9,fontWeight:500,letterSpacing:"0.05em",textTransform:"uppercase",color:"rgba(255,255,255,0.35)",margin:0}}>{sec.title}</h2><SB value={act.scores?.[sec.sk]||0}/></div><span style={{color:"rgba(255,255,255,0.15)",fontSize:10}}>{o?"▾":"▸"}</span></div>{o&&<div style={{paddingBottom:10}}><div style={{display:"flex",alignItems:"center",gap:5,marginBottom:6}}><span style={{fontSize:9,color:"rgba(255,255,255,0.2)"}}>Score</span><input type="number" min="0" max="10" style={{...inp,width:44,textAlign:"center",fontFamily:F}} value={act.scores?.[sec.sk]||""} onChange={e=>uS(sec.sk,e.target.value)}/></div>{sec.metrics.map(m=><div key={m.key} style={{marginBottom:4}}><label style={lb}>{m.label}</label>{m.type==="text"?<textarea style={{...inp,height:44,resize:"vertical",lineHeight:1.4}} value={act.metrics?.[m.key]||""} onChange={e=>uM(m.key,e.target.value)}/>:<input type="number" step="any" style={{...inp,fontFamily:F}} value={act.metrics?.[m.key]||""} onChange={e=>uM(m.key,e.target.value)}/>}</div>)}</div>}</div>)})}
  <div style={{padding:"10px 0",borderTop:"1px solid rgba(255,255,255,0.04)"}}><h2 style={{fontFamily:F,fontSize:9,fontWeight:500,letterSpacing:"0.05em",textTransform:"uppercase",color:"rgba(255,255,255,0.35)",margin:"0 0 6px"}}>Business Quality</h2><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{QL.map(q=><button key={q.value} onClick={()=>setAct(p=>({...p,quality:q.value}))} style={{padding:"5px 10px",borderRadius:4,border:act.quality===q.value?`1px solid ${q.color}`:"1px solid rgba(255,255,255,0.06)",background:act.quality===q.value?q.color+"18":"transparent",color:act.quality===q.value?q.color:"rgba(255,255,255,0.35)",fontSize:11,cursor:"pointer",fontFamily:B,fontWeight:act.quality===q.value?600:400}}>{q.label}</button>)}</div></div>
  <div style={{padding:"10px 0",borderTop:"1px solid rgba(255,255,255,0.04)"}}><h2 style={{fontFamily:F,fontSize:9,fontWeight:500,letterSpacing:"0.05em",textTransform:"uppercase",color:"rgba(255,255,255,0.35)",margin:"0 0 6px"}}>Price Level</h2><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{PL.map(p=><button key={p.value} onClick={()=>setAct(pr=>({...pr,price_level:p.value}))} style={{padding:"5px 10px",borderRadius:4,border:act.price_level===p.value?`1px solid ${p.color}`:"1px solid rgba(255,255,255,0.06)",background:act.price_level===p.value?p.color+"18":"transparent",color:act.price_level===p.value?p.color:"rgba(255,255,255,0.35)",fontSize:11,cursor:"pointer",fontFamily:B,fontWeight:act.price_level===p.value?600:400}}>{p.label}</button>)}</div>{act.quality&&act.price_level&&<div style={{marginTop:6,padding:"6px 8px",borderRadius:5,background:"rgba(255,255,255,0.02)",border:`1px solid ${gv(act.quality,act.price_level).c}22`}}><VB quality={act.quality} price_level={act.price_level}/></div>}</div>
  <div style={{padding:"8px 0",borderTop:"1px solid rgba(255,255,255,0.04)"}}><label style={lb}>Bull</label><textarea style={{...inp,height:44,resize:"vertical",lineHeight:1.4}} value={act.bull||""} onChange={e=>setAct(p=>({...p,bull:e.target.value}))}/><label style={{...lb,marginTop:4}}>Bear</label><textarea style={{...inp,height:44,resize:"vertical",lineHeight:1.4}} value={act.bear||""} onChange={e=>setAct(p=>({...p,bear:e.target.value}))}/></div>
  <div style={{display:"flex",gap:6,margin:"12px 0 40px",justifyContent:"flex-end"}}><button onClick={()=>setView("list")} style={{...btn,background:"transparent",border:"1px solid rgba(255,255,255,0.06)",color:"rgba(255,255,255,0.3)"}}>Cancel</button><button onClick={doSv} style={{...btn,background:"#22c55e",color:"#09090b",fontWeight:600}}>Save</button></div></div></div>)}

  return (<div style={base}>{fonts}<div style={{maxWidth:640,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div><h1 style={{fontFamily:F,fontSize:16,fontWeight:600,margin:0}}>Stock Scorecards</h1><p style={{margin:"2px 0 0",fontSize:9,color:"rgba(255,255,255,0.18)"}}>{cards.length} stocks · sorted by composite · May 2026</p></div><button onClick={()=>{setAct(empty());setOs(null);setView("edit");}} style={{...btn,background:"#22c55e",color:"#09090b",fontWeight:600,fontSize:11}}>+ New</button></div>
  {cmp.length>=2&&<button onClick={()=>setView("compare")} style={{...btn,background:"#3b82f6",color:"#fff",fontWeight:500,width:"100%",marginBottom:6,fontSize:12}}>Compare {cmp.length} →</button>}
  <div style={{display:"flex",flexDirection:"column",gap:3}}>{cards.map(c=>{const a=cavg(c.scores);const s=cmp.includes(c.id);return (<div key={c.id} style={{background:s?"rgba(59,130,246,0.04)":"rgba(255,255,255,0.012)",border:s?"1px solid rgba(59,130,246,0.15)":"1px solid rgba(255,255,255,0.03)",borderRadius:6,padding:"8px 10px",display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:8,flex:1}} onClick={()=>{setAct({...c});setOs(null);setView("edit");}}><div style={{fontFamily:F,fontSize:16,fontWeight:600,width:36,textAlign:"center",color:a!=="–"?(a>=7.5?"#22c55e":a>=5?"#f59e0b":"#ef4444"):"rgba(255,255,255,0.08)"}}>{a}</div><div><div style={{fontFamily:F,fontSize:11,fontWeight:500}}>{c.ticker||"—"}</div><div style={{fontSize:9,color:"rgba(255,255,255,0.25)"}}>{c.company}</div><VB quality={c.quality} price_level={c.price_level}/></div></div><div style={{display:"flex",gap:3}}><button onClick={e=>{e.stopPropagation();tC(c.id);}} style={{...sm,background:s?"rgba(59,130,246,0.08)":"rgba(255,255,255,0.02)",color:s?"#3b82f6":"rgba(255,255,255,0.2)"}}>cmp</button><button onClick={e=>{e.stopPropagation();if(confirm(`Delete ${c.ticker}?`))dl(c.id);}} style={{...sm,color:"rgba(255,255,255,0.1)"}}>×</button></div></div>)})}</div>
  <p style={{fontSize:8,color:"rgba(255,255,255,0.1)",marginTop:12,textAlign:"center"}}>Post Q1 2026 hyperscaler earnings · prices updated May 13 2026</p></div></div>);
}
const lb={display:"block",fontSize:8,color:"rgba(255,255,255,0.25)",marginBottom:1};
const inp={width:"100%",padding:"5px 7px",fontSize:10,fontFamily:"'Inter',sans-serif",background:"rgba(255,255,255,0.02)",border:"1px solid rgba(255,255,255,0.05)",borderRadius:4,color:"#e4e4e7",outline:"none",boxSizing:"border-box"};
const btn={padding:"7px 12px",fontSize:11,borderRadius:5,border:"none",cursor:"pointer",fontFamily:"'Inter',sans-serif"};
const sm={padding:"2px 5px",fontSize:8,borderRadius:3,border:"none",cursor:"pointer",fontFamily:"'JetBrains Mono',monospace"};
const lnk={background:"none",border:"none",color:"rgba(255,255,255,0.25)",cursor:"pointer",fontSize:10,padding:0};
const th={padding:"5px 6px",textAlign:"left",borderBottom:"1px solid rgba(255,255,255,0.05)",color:"rgba(255,255,255,0.25)",fontSize:8};
const td={padding:"6px 6px",borderBottom:"1px solid rgba(255,255,255,0.02)",verticalAlign:"top",fontSize:10};
const tdL={...td,color:"rgba(255,255,255,0.25)",fontSize:8,fontFamily:"'JetBrains Mono',monospace",whiteSpace:"nowrap"};
